export const SPECTRUM_CARDS = [
  { left: "Good", right: "Bad" },
  { left: "Great sequel", right: "Poor sequel" },
  { left: "Rotten Tomato", right: "Fresh Tomato" },
  { left: "Highly addictive", right: "Mildly addictive" },
  { left: "Cold", right: "Hot" },
  { left: "Colorful", right: "Colorless" },
  { left: "High calorie", right: "Low calorie" },
  { left: "Feels good", right: "Feels bad" },
  { left: "Essential", right: "Inessential" },
  { left: "Expensive", right: "Cheap" },
  { left: "Overrated weapon", right: "Underrated weapon" },
  { left: "Hard subject", right: "Easy subject" },
  { left: "Famous", right: "Unknown" },
  { left: "Easy to use", right: "Difficult to use" },
  { left: "Strange", right: "Normal" },
  { left: "Stranger Things", right: "Normal Things" },
  { left: "Clean", right: "Dirty" },
  { left: "Requires skill", right: "Requires luck" },
  { left: "Flavorful", right: "Flavorless" },
  { left: "Fascinating topic", right: "Boring topic" },
  { left: "Good actors", right: "Bad actor" },
  { left: "Hipster", right: "Basic" },
  { left: "Safe job", right: "Dangerous job" },
  { left: "Sci-Fi", right: "Fantasy" },
  { left: "Formal", right: "Casual" },
  { left: "Overpaid", right: "Underpaid" },
  { left: "Wet", right: "Dry" },
  { left: "Overrated skill", right: "Underrated skill" },
  { left: "Encouraged", right: "Forbidden" },
  { left: "Happy song", right: "Sad song" },
  { left: "Durable", right: "Fragile" },
  { left: "Dork", right: "Geek" },
  { left: "Evil", right: "Good" },
  { left: "Best day of the year", right: "Worst day of the year" },
  { left: "Good habit", right: "Bad habit" },
  { left: "Dog person", right: "Cat person" },
  { left: "Openly love", right: "Guilty pleasure" },
  { left: "Talented", right: "Untalented" },
  { left: "Light", right: "Dark" },
  { left: "Overrated actor", right: "Underrated actor" },
  { left: "Easy to find", right: "Hard to find" },
  { left: "Beautiful man", right: "Ugly man" },
  { left: "Easy to remember", right: "Hard to remember" },
  { left: "Highbrow", right: "Lowbrow" },
  { left: "Healthy", right: "Unhealthy" },
  { left: "Good man", right: "Bad man" },
  { left: "Historically irrelevant", right: "Historically important" },
  { left: "Hairy", right: "Hairless" },
  { left: "Flexible", right: "Inflexible" },
  { left: "Exotic pet", right: "Common pet" },
  { left: "Good Pet", right: "Bad Pet" },
  { left: "Extrovert", right: "Introvert" },
  { left: "Movie was better", right: "Book was better" },
  { left: "Good movie", right: "Bad movie" },
  { left: "Beautiful", right: "Ugly" },
  { left: "Happens suddenly", right: "Happens slowly" },
  { left: "Career", right: "Job" },
  { left: "Hated", right: "Loved" },
  { left: "The Dark Side of the Force", right: "The Light Side of the Force" },
  { left: "Good pizza topping", right: "Bad pizza topping" },
  { left: "Utopia", right: "Dystopia" },
  { left: "Immature person", right: "Mature person" },
  { left: "Overrated thing to own", right: "Underrated thing to own" },
  { left: "Nice person", right: "Mean person" },
  { left: "Adventure movie", right: "Action movie" },
  { left: "Sexy", right: "Unsexy" },
  { left: "Wired", right: "Tired" },
  { left: "Abundant", right: "Scarce" },
  { left: "Common", right: "Ulta rare" },
  { left: "Believable", right: "Unbelievable" },
  { left: "Classy", right: "Trashy" },
  { left: "Permanent", right: "Temporary" },
  { left: "Doesn't look like a person", right: "Looks like a person" },
  { left: "Tastes good", right: "Tastes bad" },
  { left: "Game", right: "Sport" },
  { left: "Overrated Game", right: "Underrated Game" },
  { left: "Order of the Phoenix", right: "Death Eaters" },
  { left: "Jedi", right: "Sith" },
  { left: "Cool", right: "Uncool" },
  { left: "Greatest living person", right: "Worst living person" },
  { left: "Overrated", right: "Underrated" },
  { left: "Clean food", right: "Messy food" },
  { left: "Ethical", right: "Unethical" },
  { left: "Good gift", right: "Bad gift" },
  { left: "Fashionable", right: "Unfashionable" },
  { left: "Forgiveable", right: "Unforgiveable" },
  { left: "Harmful", right: "Harmless" },
  { left: "Hygienic", right: "Unhygienic" },
  { left: "Good music", right: "Bad music" },
  { left: "Useful", right: "Useless" },
  { left: "Art", right: "Science" },
  { left: "Important", right: "Unimportant" },
  { left: "Hard to spell", right: "Easy to spell" },
  { left: "Virtue", right: "Vice" },
  { left: "Overrated musician", right: "Underrated musician" },
  { left: "Popular activity", right: "Unpopular activity" },
  { left: "Whole", right: "Divided" },
  { left: "Reliable", right: "Unreliable" },
  { left: "Hard to kill", right: "Easy to kill" },
  { left: "Stable", right: "Unstable" },
  { left: "Pointy animal", right: "Round animal" },
  { left: "Good TV show", right: "Bad TV show" },
  { left: "Feminine", right: "Masculine" },
  { left: "Useful body part", right: "Useless body part" },
  { left: "Classic", right: "Fad" },
  { left: "Brilliant", right: "Stupid" },
  { left: "Strong", right: "Weak" },
  { left: "Useful invention", right: "Useless invention" },
  { left: "Conservative", right: "Liberal" },
  { left: "Popular", right: "Unpopular" },
  { left: "Enemy", right: "Friend" },
  { left: "Exciting", right: "Boring" },
  { left: "Smelly in a good way", right: "Smelly in a bad way" },
  { left: "Hero", right: "Villain" },
  { left: "Can't afford to lose", right: "Want to lose" },
  { left: "Necessary habit", right: "Unnecessary habit" },
  { left: "Impressive Hero", right: "Pathetic Hero" },
  { left: "Overrated thing to do", right: "Underrated thing to do" },
  { left: "Useful Tech", right: "Useless Tech" },
  { left: "Useful in an emergency", right: "Useless in an emergency" },
  { left: "For adults", right: "For kids" },
  { left: "Hard to do", right: "Easy to do" },
  { left: "Priceless", right: "Worthless" },
  { left: "Nurture", right: "Nature" },
  { left: "Democracy", right: "Dictatorship" },
  { left: "Cat name", right: "Dog name" },
  { left: "Partisan", right: "Non-partisan" },
  { left: "Infinite", right: "Limited" },
  { left: "Formal event", right: "Casual event" },
  { left: "Good investment", right: "Bad investment" },
  { left: "Heavy topic", right: "Small talk" },
  { left: "Spicy", right: "Mild" },
  { left: "Sacrilegious", right: "Religious" },
  { left: "Art", right: "Not art" },
  { left: "Prohibited", right: "Illegal" },
  { left: "Elitist", right: "Popular" },
  { left: "In control", right: "Out of control" },
  { left: "Loud", right: "Quiet" },
  { left: "Public knowledge", right: "Secret" },
  { left: "Too big", right: "Too small" },
  { left: "Long", right: "Short" },
  { left: "Best year in history", right: "Worst year in history" },
  { left: "Capitalist", right: "Socialist" },
  { left: "Well known fact", right: "Little known fact" },
  { left: "Mobile", right: "Stationary" },
  { left: "Global issue", right: "Local issue" },
  { left: "Skill", right: "Talent" },
  { left: "Best era to time travel", right: "Worst era to time travel" },
  { left: "The best", right: "The worst" },
  { left: "Large number", right: "Small number" },
  { left: "False", right: "True" },
  { left: "Avant garde", right: "Old fashioned" },
  { left: "Beautiful word", right: "Ugly word" },
  { left: "Tiny", right: "Small" },
  { left: "Natural", right: "Unnatural" },
  { left: "Phony", right: "Genuine" },
  { left: "Original", right: "Derivative" },
  { left: "Benefits everyone", right: "Benefits you" },
  { left: "Powerful", right: "Powerless" },
  { left: "Vegetable", right: "Fruit" },
  { left: "Pseudoscience", right: "Science" },
  { left: "Serious topic", right: "Funny topic" },
  { left: "Firm", right: "Limp" },
  { left: "News", right: "Gossip" },
  { left: "Easy to sit on", right: "Hard to sit on" },
  { left: "Too much", right: "Not enough" },
  { left: "Vertical", right: "Horizontal" },
  { left: "Scented", right: "Unscented" },
  { left: "Not huggable", right: "Huggable" },
  { left: "Homogenous", right: "Heterogeneous" },
  { left: "Exclusive", right: "Inclusive" },
  { left: "Good dog breed", right: "Bad dog breed" },
  { left: "Commerce", right: "Art" },
  { left: "Pop icon", right: "One hit wonder" },
  { left: "Good advice", right: "Bad advice" },
  { left: "Good candy", right: "Bad candy" },
  { left: "Radical", right: "Traditional" },
  { left: "Good mouthfeel", right: "Bad mouthfeel" },
  { left: "Legal", right: "Illegal" },
  { left: "Shallow", right: "Deep" },
  { left: "Always on time", right: "Never on time" },
  { left: "Strange", right: "Weird" },
  { left: "Infamous", right: "Famous" },
  { left: "Fun", right: "Boring" },
  { left: "Best chore", right: "Worst chore" },
  { left: "Overpopulated", right: "Endangered" },
  { left: "Green", right: "Blue" },
  { left: "Terrifying", right: "Soothing" },
  { left: "Unexpected", right: "Expected" },
  { left: "Good Website", right: "Bad Website" },
  { left: "Romantic Movie", right: "Unromantic Movie" }
];
